version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
     - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    restart: on-failure
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
  # ******* BONUS *******
  redis:
    image: redis
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - my-net
    env_file:
      - .env
    restart: on-failure
  ftp:
    image: ftp
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "21:21"
    env_file:
      - .env
    restart: on-failure
  static_website:
    image: static_website
    container_name: static_website
    build:
      context: ./requirements/bonus/static_website
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: on-failure
  adminer:
    image: adminer
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-net
    env_file:
      - .env
    restart: on-failure
  cadvisor:
    image: cadvisor
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/okhiar/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/okhiar/data/wordpress'

networks:
  my-net:
    driver: bridge
